---
- name: devtoolset-4 | Install devtoolset-4
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl
    - devtoolset-4
  become: yes

- name: devtoolset-4 | Remove Java packages which break Jenkins
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - rh-java-common-runtime
  become: yes
