---
- name: devtoolset-7 | Install devtoolset-7
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl
    - devtoolset-7
  become: yes

- name: devtoolset-7 | Remove Java packages which break Jenkins
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - rh-java-common-runtime
  become: yes
