---
# tasks file for roles/omero-web-apps-build-dependencies
# if the os is centOS

- name: system packages | install epel repo
  become: yes
  yum:
    name: epel-release
    state: present

- name: system packages | install build tools
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ant
    - ant-contrib

- name: Install nodejs
  become: yes
  yum:
    enablerepo: epel
    name: nodejs
    state: present

- name: Install npm
  become: yes
  yum:
    name: npm
    state: present

- name: Install grunt command line tool
  become: yes
  npm: 
    name: grunt-cli
    global: yes
