# Test redirects
#
# Test the default host:
#   pytest check_redirects.py
#
# Test a different host:
#   HOST=http://www-dev.openmicroscopy.org pytest check_redirects.py

import os
import pytest
import requests


HOST = os.getenv('HOST', 'https://infra-testpr.openmicroscopy.org')


# Based on
# https://github.com/sbesson/infrastructure/blob/3fd40a3ad61a0f496b4815e4abbeadca798ce210/ansible/server-state-playbooks/www-dev/www-dev.yml#L172
@pytest.mark.parametrize('uri,expect', [
    ('/site', '/'),
    ('/site/about/licensing-attribution', '/licensing'),
    ('/site/about/ome-contributors', '/contributors'),
    ('/site/about/partners', '/commercial-partners'),
    ('/site/about/development-teams', '/teams'),

    ('/site/community', '/support'),
    ('/site/community/mailing-lists', '/support'),
    ('/site/community/jobs', '/careers'),

    ('/site/support', '/docs'),
    ('/site/news', '/announcements'),
])
@pytest.mark.parametrize('suffix', ['', '/'])
def test_redirect_with_slash(uri, expect, suffix):
    r = requests.head('%s%s%s' % (HOST, uri, suffix))
    assert r.is_redirect
    assert r.headers['Location'] == '%s%s' % (HOST, expect)


def test_404():
    uri = '/non-existent/path'
    r = requests.head('%s%s' % (HOST, uri))
    assert r.status_code == 404


@pytest.mark.parametrize('uri,content', [
    ('/community', 'This page was generated by phpBB'),
    ('/community/ucp.php?mode=login', ' Login</title>'),
    ('/community/viewtopic.php?f=6&t=8319',
     'UserId issues from Matlab.</title>'),
    ('/community/viewtopic.php?f=11&t=8320',
     'View topic - Release of Bio-Formats 5.5.3</title>'),
    ('/community/viewtopic.php?p=18303#p18303',
     '<div id="p18303" class="post bg1">'),
    ('/community/index.php', 'Index page</title>'),
])
def test_content(uri, content):
    r = requests.get('%s%s' % (HOST, uri))
    assert content in r.text
