---
# Prerequisites required for this Ansible role

- name: omero | install selinux utilities
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
  when: omero_selinux_setup
