---
# tasks file for roles/python

- name: python packages | install python tools
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-devel
    - python-pip
    - python-virtualenv
