---
# Playbook for creating OpenStack IDR VMs
# TODO: Consider making some of this into a role, so that it's easier to
# switch variables for different clouds

- hosts: localhost
  connection: local
  #gather_facts: false

  vars:

    # idr_environment: All VMs will be put into this group, which should have
    # a matching group_vars file
    omero_vm_groups: "ansible-managed,os-image-centos,omero-hosts,{{ idr_environment | default('os-idr') }}"
    omero_vm_extra_groups: ""
    gateway_vm_groups: "ansible-managed,os-image-centos,proxy-hosts,{{ idr_environment | default('os-idr') }}"
    database_vm_groups: "ansible-managed,os-image-centos,database-hosts,{{ idr_environment | default('os-idr') }}"

    #vm_prefix:
    #vm_key_name:
    ignore_internal_known_hosts: True

  # If os_cloud_provider.yml exists load it, otherwise default to default.yml
  # Note that if an invalid os_cloud_provider is given this will fallback
  # to default.yml
  vars_files:
    - [ "{{ inventory_dir }}/vars/os-create-{{ os_cloud_provider }}.yml", "vars/os-create-default.yml" ]

  pre_tasks:

    - fail:
        msg: "vm_key_name is required"
      when: vm_key_name is undefined or not vm_key_name

    - fail:
        msg: "vm_prefix is required"
      when: vm_prefix is undefined or not vm_prefix


  tasks:

    # If True (default) a single gateway will be setup
    # Set this to False if every instance has a floating IP
    - set_fact:
        single_floating_ip: True
      when: single_floating_ip is not defined

    - set_fact:
        assign_floating_ip: "{{ not (single_floating_ip | bool) }}"

    - set_fact: omero_vm_joined_groups="{{ omero_vm_groups.split(',') | union(omero_vm_extra_groups.split(',')) | join(',')}}"

    # The rules on conversion to booleans are confusing, check
    - debug:
        msg: "single_floating_ip:{{ single_floating_ip | bool }} assign_floating_ip:{{ assign_floating_ip }}"
        verbosity: 1

    - name: OMERO external access security group
      os_security_group:
        description: External access to OMERO servers (managed by Ansible)
        name: omero-external
        state: present

    - name: OMERO external access security group rules
      os_security_group_rule:
        direction: ingress
        port_range_max: "{{ item }}"
        port_range_min: "{{ item }}"
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        security_group: omero-external
        state: present
      with_items:
        - 22
        - 80
        - 443
        - 4063
        - 4064

    - name: Gateway external access security group
      os_security_group:
        description: External access to Ogateway servers (managed by Ansible)
        name: gateway-external
        state: present

    - name: Gateway external access security group rules
      os_security_group_rule:
        direction: ingress
        port_range_max: "{{ item }}"
        port_range_min: "{{ item }}"
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        security_group: gateway-external
        state: present
      with_items:
        - 22
        - 80
        - 443

    - name: OMERO VM
      os_server:
        name: "{{ omero_vm_name }}"
        state: present
        image: "{{ vm_image }}"
        key_name: "{{ vm_key_name }}"
        flavor: "{{ omero_vm_flavour }}"
        nics: "{{ omero_vm_private_network | default(omit) }}"
        auto_ip: "{{ assign_floating_ip }}"
        meta:
          hostname: "{{ omero_vm_name }}"
          groups: "{{ omero_vm_joined_groups }}"
        security_groups: [default, omero-external]
      register: vmomero

    - name: Database VM
      os_server:
        name: "{{ database_vm_name }}"
        state: present
        image: "{{ vm_image }}"
        key_name: "{{ vm_key_name }}"
        flavor: "{{ database_vm_flavour }}"
        nics: "{{ vm_private_network | default(omit) }}"
        auto_ip: "{{ assign_floating_ip }}"
        meta:
          hostname: "{{ database_vm_name }}"
          groups: "{{ database_vm_groups }}"
        security_groups: [default]
      register: vmdatabase

    - name: Gateway VM
      os_server:
        name: "{{ gateway_vm_name }}"
        state: present
        image: "{{ vm_image }}"
        key_name: "{{ vm_key_name }}"
        nics: "{{ vm_private_network | default(omit) }}"
        flavor: "{{ gateway_vm_flavour }}"
        auto_ip: yes
        meta:
          hostname: "{{ gateway_vm_name }}"
          groups: "{{ gateway_vm_groups }}"
        security_groups: [default, gateway-external]
      register: vmgateway

    # The gateway should always have a floating IP.
    # If other instances also have a floating IP we can connect directly to
    # them, otherwise we need to connect via the gateway

    - name: SSH public or private IP
      set_fact:
        ssh_public_private: "{{ (single_floating_ip | bool ) | ternary('private_v4', 'public_v4') }}"

    - name: SSH gateway proxy args
      set_fact:
        ssh_gateway_proxy: >
          -o ProxyCommand="ssh -W %h:%p centos@{{ vmgateway.server.public_v4 }}"
          {{ ignore_internal_known_hosts |
          ternary("-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no", "")}}
      when: (single_floating_ip | bool)

    # To prevent duplicates with the dynamic inventory only add_host if
    # the VM was created in this run

    - name: Gateway VM hosts file
      add_host:
        name: "{{ gateway_vm_name }}"
        groups: "{{ gateway_vm_groups }}"
        ansible_host: "{{ vmgateway.server[ssh_public_private] }}"
        ansible_user: centos
        ansible_become: true
        ansible_ssh_common_args: "{{ ssh_gateway_proxy | default(omit) }}"
      when: vmgateway.changed

    - name: OMERO VM hosts files
      add_host:
        name: "{{ omero_vm_name }}"
        groups: "{{ omero_vm_joined_groups }}"
        ansible_host: "{{ vmomero.server[ssh_public_private] }}"
        ansible_user: centos
        ansible_become: true
        ansible_ssh_common_args: "{{ ssh_gateway_proxy | default(omit) }}"
      when: vmomero.changed

    - name: Database VM hosts files
      add_host:
        name: "{{ database_vm_name }}"
        groups: "{{ database_vm_groups }}"
        ansible_host: "{{ vmdatabase.server[ssh_public_private] }}"
        ansible_user: centos
        ansible_become: true
        ansible_ssh_common_args: "{{ ssh_gateway_proxy | default(omit) }}"
      when: vmdatabase.changed

    - debug:
        msg: "IPs (OMERO) private:{{ vmomero.openstack.private_v4 }} floating:{{ vmomero.openstack.public_v4 | default('') }}"

    - debug:
        msg: "IPs (database) private:{{ vmdatabase.openstack.private_v4 }} floating:{{ vmdatabase.openstack.public_v4 | default('') }}"

    - debug:
        msg: "IPs (gateway) private:{{ vmgateway.openstack.private_v4 }} floating:{{ vmgateway.openstack.public_v4 | default('') }}"
