---
# Playbook for creating OpenStack IDR volumes

- hosts: localhost
  connection: local
  #gather_facts: false

  # If os_cloud_provider.yml exists load it, otherwise default to default.yml
  # Note that if an invalid os_cloud_provider is given this will fallback
  # to default.yml
  vars_files:
    - [ "{{ inventory_dir }}/vars/os-create-{{ os_cloud_provider }}.yml", "vars/os-create-default.yml" ]

  roles:

  - role: openstack-volume-storage
    openstack_volume_size: 100
    openstack_volume_vmname: "{{ database_vm_name }}"
    openstack_volume_name: db
    openstack_volume_device: /dev/vdb

  - role: openstack-volume-storage
    openstack_volume_size: 100
    openstack_volume_vmname: "{{ omero_vm_name }}"
    openstack_volume_name: data
    openstack_volume_device: /dev/vdb

  - role: openstack-volume-storage
    openstack_volume_size: 20
    openstack_volume_vmname: "{{ gateway_vm_name }}"
    openstack_volume_name: nginxcache
    openstack_volume_device: /dev/vdb
