---
# tasks file for roles/omero-runtime


- name: omero python deps | pypi pillow uninstall
  become: yes
  pip:
    name: "{{ item }}"
    state: absent
  with_items:
  - "Pillow"

- name: omero python deps | distribution packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Cython
    - numpy
    - python-pillow
    - python-matplotlib
    - python-numexpr
    - python-tables
    - python-pip
    - scipy
  when: "{{ omero_python_deps_recommended }}"
