# Test redirects
#
# Test the default host:
#   pytest check_redirects.py
#
# Test a different host:
#   HOST=http://www-dev.openmicroscopy.org pytest check_redirects.py

import os
import pytest
import requests


HOST = os.getenv('HOST', 'https://ome-www.openmicroscopy.org')
LEGACY_HOST = os.getenv('LEGACY_HOST', 'https://www-legacy.openmicroscopy.org')


# Based on
# https://github.com/openmicroscopy/infrastructure/blob/master/ansible/server-state-playbooks/www/www.yml
@pytest.mark.parametrize('uri,expect', [
    ('/site', '/'),
    ('/site/about/licensing-attribution', '/licensing'),
    ('/site/about/ome-contributors', '/contributors'),
    ('/site/about/partners', '/commercial-partners'),
    ('/site/about/development-teams', '/teams'),

    ('/site/community', '/support'),
    ('/site/community/mailing-lists', '/support'),
    ('/site/community/jobs', '/careers'),

    ('/site/products', '/products'),
    ('/site/products/bio-formats', '/bio-formats'),
    ('/site/products/omero', '/omero'),

    ('/site/support', '/docs'),
    ('/site/news', '/announcements'),
])
@pytest.mark.parametrize('suffix', ['', '/'])
def test_redirect_with_slash(uri, expect, suffix):
    r = requests.head('%s%s%s' % (HOST, uri, suffix))
    assert r.is_redirect
    assert r.headers['Location'] == '%s%s' % (HOST, expect)


@pytest.mark.parametrize('uri', [
    '/site/about/publications',
    '/site/community/scripts',
    '/site/products/partner',
    '/site/support/omero5.3',
    '/site/support/bio-formats5.5',
    ])
@pytest.mark.parametrize('suffix', ['', '/'])
def test_legacy_redirects(uri, suffix):
    r = requests.head('%s%s%s' % (HOST, uri, suffix))
    assert r.is_redirect
    assert r.headers['Location'] == '%s%s%s' % (LEGACY_HOST, uri, suffix)


def test_404():
    uri = '/non-existent/path'
    r = requests.head('%s%s' % (HOST, uri))
    assert r.status_code == 404


@pytest.mark.parametrize('uri,content', [
    ('/community', 'This page was generated by phpBB'),
    ('/community/ucp.php?mode=login', ' Login</title>'),
    ('/community/viewtopic.php?f=6&t=8319',
     'UserId issues from Matlab.</title>'),
    ('/community/viewtopic.php?f=11&t=8320',
     'View topic - Release of Bio-Formats 5.5.3</title>'),
    ('/community/viewtopic.php?p=18303#p18303',
     '<div id="p18303" class="post bg1">'),
    ('/community/index.php', 'Index page</title>'),
    ('/Schemas/', 'Open Microscopy Environment Schemas</title>'),
    ('/Schemas/OME/2016-06/ome.xsd', 'Schema June 2016'),
])
def test_content(uri, content):
    r = requests.get('%s%s' % (HOST, uri))
    assert content in r.text
