---
# Playbook for starting an IDR-like OMERO in the UoD
# openstack cloud.

- include: os-idr-playbooks/os-create.yml
  vars:
    omero_vm_extra_groups: "uod-nfs,idr-hosts"
    os_cloud_provider: uod

- include: os-idr-playbooks/os-volumes.yml
  vars:
    os_cloud_provider: uod

- include: idr-playbooks/idr-local-users.yml
# Variables for this section are in a private file

- hosts: database-hosts
  roles:
  - role: storage-volume-initialise
    storage_volume_initialise_device: /dev/vdb
    storage_volume_initialise_mount: /var/lib/pgsql

- hosts: omero-hosts
  roles:
  - role: storage-volume-initialise
    storage_volume_initialise_device: /dev/vdb
    storage_volume_initialise_mount: /data

- hosts: proxy-hosts
  roles:
  - role: storage-volume-initialise
    storage_volume_initialise_device: /dev/vdb
    storage_volume_initialise_mount: /var/cache/nginx

- include: idr-playbooks/idr-dundee-nfs.yml

- include: idr-playbooks/idr-omero.yml
# Vars are in os-omero.yml so that the playbook can be run independently

- include: idr-playbooks/idr-local-files.yml

- include: idr-playbooks/idr-user-utils.yml

#- include: idr-playbooks/idr-monitoring.yml
