# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
#
# See: http://docs.ansible.com/ansible/guide_vagrant.html
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/7"
    docker.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "postgres" do |postgres|
    postgres.vm.box = "centos/7"
    postgres.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "redis" do |redis|
    redis.vm.box = "centos/7"
    redis.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "samba" do |samba|
    samba.vm.box = "centos/7"
    samba.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "cliutils" do |cliutils|
    cliutils.vm.box = "centos/7"
    cliutils.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "test.yml"
    end
  end

  config.vm.define "training-server" do |training|
    training.vm.box = "centos/7"
    training.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "training-server.yml"
    end
  end

  # IDR multinode omero
  ["idr-database", "idr-omero", "idr-gateway"].each do |s|
    config.vm.define "#{s}" do |node|
      node.vm.box = "centos/7"
      node.vm.network "private_network", type: "dhcp"
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
      end
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "idr-playbooks/idr-omero.yml"
        ansible.limit = "idr"
        ansible.groups = {
          "idr-database-hosts" => ["idr-database"],
          "idr-omero-hosts" => ["idr-omero"],
          "idr-proxy-hosts" => ["idr-gateway"],
          "idr:children" => ["idr-database-hosts", "idr-omero-hosts", "idr-proxy-hosts"],
          "idr:vars" => {
            # Vagrant uses eth0 for NAT, eth1 for private guest network
            "idr_net_iface" => "eth1",
            "idr_nginx_ssl_self_signed" => "True",
            "omero_release" => "0.0.7-rc1",
            "omero_omego_additional_args" => "--downloadurl https://downloads.openmicroscopy.org/idr",
          }
        }
      end
    end
  end


  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

end
