# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
#
# See: http://docs.ansible.com/ansible/guide_vagrant.html
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.provider :openstack do |os, override|
    override.ssh.username = "centos"
    # Workaround sudo restriction
    override.ssh.pty = true

    os.openstack_auth_url = "#{ENV['OS_AUTH_URL']}"
    os.username = "#{ENV['OS_USERNAME']}"
    os.password = "#{ENV['OS_PASSWORD']}"
    os.tenant_name = "#{ENV['OS_TENANT_NAME']}"
    os.region = "#{ENV['OS_REGION_NAME']}"

    os.flavor = 'm1.small'
    os.image = 'CentOS 7 1607'
    os.floating_ip_pool = 'external_network'
  end

  [
    "cliutils",
    "docker",
    "docs",
    "jupyter",
    "postgres",
    "redis",
    "samba",
    "selinux",
    "omerowebappsbuilddependencies"
  ].each do |server|
    config.vm.define "#{server}" do |node|
      node.vm.box = "centos/7"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "test.yml"
      end
    end
  end

  [
    "omeroscriptsdependencies-debian"
  ].each do |server|
    config.vm.define "#{server}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "test.yml"
      end
    end
  end

  [
    "haproxy",
    "java",
    "nginx",
    "nginx-mainline",
    "omero-server-ice35",
    "omero-server-ice36",
  ].each do |server|
    config.vm.define "#{server}" do |node|
      node.vm.box = "centos/7"
      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "tests/#{server}.yml"
      end
    end
  end

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

end
