---
# tasks file for roles/nginx-proxy

- name: nginx | main config
  become: yes
  template:
    src: nginx-conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

# See http://serverfault.com/a/337893
- name: nginx | proxy config
  become: yes
  template:
    src: nginx-confd-proxy.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify:
    - restart nginx
  when: nginx_proxy_backends

- name: nginx | dynamic proxy config
  become: yes
  file:
    dest: /etc/nginx/conf.d/proxy.conf
    state: absent
  notify:
    - restart nginx
  when: not nginx_proxy_backends

- name: nginx | Remove old proxy config
  become: yes
  file:
    dest: /etc/nginx/conf.d/dynamic-proxy.conf
    state: absent
  notify:
    - restart nginx

- include: nginx-cache.yml

- include: nginx-ssl-certs.yml

- name: nginx | start service
  become: yes
  service:
    enabled: yes
    name: nginx
    state: started
